"""Registre de tous les moteurs SAFE (contre-parties sécurisées)."""
from . import (
    sqli, cmdi, insecdeser, insecupload, bufovr, credsexpose, brokenauth,
    xss, dirtrav, xxe, nosqli, ldapi, insecperm, idor, sessfix, ssrf, ssti,
    proto_pollution, http_smuggling, xpath_injection, graphqli, cors, csrf,
    ratelimit, infodisc, insec_crypto, open_redirect, jwt_vuln,
    crlf_injection, race_condition,
)

ENGINES = {
    "SQLi": sqli,
    "CMDi": cmdi,
    "InsecDeser": insecdeser,
    "InsecUpload": insecupload,
    "BufOvr": bufovr,
    "CredsExpose": credsexpose,
    "BrokenAuth": brokenauth,
    "XSS": xss,
    "DirTrav": dirtrav,
    "XXE": xxe,
    "NoSQLi": nosqli,
    "LDAPi": ldapi,
    "InsecPerm": insecperm,
    "IDOR": idor,
    "SessFix": sessfix,
    "SSRF": ssrf,
    "SSTI": ssti,
    "Prototype_Pollution": proto_pollution,
    "HTTP_Request_Smuggling": http_smuggling,
    "XPATH_Injection": xpath_injection,
    "GraphQLi": graphqli,
    "CORS": cors,
    "CSRF": csrf,
    "RateLimit": ratelimit,
    "InfoDisc": infodisc,
    "InsecCrypto": insec_crypto,
    "OpenRedirect": open_redirect,
    "JWT": jwt_vuln,
    "CRLF_Injection": crlf_injection,
    "RaceCondition": race_condition,
}
